import "@/style/global.scss";
import { Plus_Jakarta_Sans } from "next/font/google";
import Header from "@/components/Header";
const plus_jakarta_sans = Plus_Jakarta_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Asim Rasheed",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={plus_jakarta_sans.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
